[[edge_functions]]
  path = "/js-hello"
  function = "js_hello"

[[edge_functions]]
  path = "/ts-hello"
  function = "ts_hello"

[context.deploy-preview.environment]
  MY_COOL_VAR = "DP_VALUE"

[context.branch-deploy.environment]
  MY_COOL_VAR = "BD_VALUE"

[context.feature.environment]
  MY_COOL_VAR = "FEATURE_VALUE"

[context.tomlbranch.environment]
  MY_COOL_VAR = "STAGING_VALUE"
  TOMLBRANCH = "YES" 

[context.branch2.environment]
  MY_COOL_VAR = "STAGING_VALUE"
  TOMLBRANCH = "YES"

[context.anotherfeature.environment]
  MY_COOL_VAR = "ANOTHER_FEATURE_VALUE"

[build.environment]
  BUILD_ENV = "VAR"
  MY_COOL_VAR = "ALL?"
  TOMLBRANCH = "NO" 
